### ISSUE TITLE
organize backup restore process

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/minio-storage#1]
we should be able to backup and restore any shared volumes to persist the state.
the same for configuration env files

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/minio-storage/commit/635b38ef3bea5e1251439fcc03478eb19d58ad9b

valid testing scenario should be able to do when 1.8 reporting and qps-infra 5.2 are ready (as minimal beta builds).

testing steps:
1) start qps-infra
2) launch web test with auto_screenshots=true
-> make sure screenshots are uploaded and visible in test info page
3) backup everything
```
./zebrunner backup
```
4) shutdown everything
```
./zebrunner.sh shutdown
```
4) setup and start again
-> nothing in test runs as everything clear

5) restore and restart everything
```
./zebrunner.sh restore
./zebrunner.sh restart
```
-> previously registered test run should be displayed, screenshots attached and visible

**Comment by ghost** [comment]
Issue with step 2
launch web test with auto_screenshots=true
-> make sure screenshots are uploaded and visible in test info page
This ticket will be verified after fix issues with test run logs in reporting.

**Comment by ghost** [comment]
https://github.com/zebrunner/reporting/issues/2195

**Comment by ghost** [comment]
Verified. Pictures are restored.
