### ISSUE TITLE
Reporting:Unable to load provider configs in Tests 

### ISSUE THREAD

**Issue by ghost** [zebrunner/minio-storage#2]
**Description**
Unable to load provider configs in Tests 

**Steps to reproduce**

1. Go to 'Reporting test runs' page
2. Click on 'Launcher'
3. Click on Api demo test
4. Verify that providers are loaded and visible

**Actual behavior**
Unable to load provider configs

**Expected behavior (if known)**
Unable to load provider configs

**Environment**

UI version:1.10
API (back-end) version:1.10.1

<img width="1023" alt="Screen Shot 2020-09-29 at 3 27 02 PM" src="https://user-images.githubusercontent.com/32964663/94569264-309e2880-0276-11eb-8a3e-d72a22d1d371.png">

**Comment by vdelendik** [comment]
default data uploaded. need to identify why data is not accessible from reporting

**Comment by vdelendik** [comment]
fixed: https://github.com/zebrunner/minio-storage/commit/6edd4b3c346da7f46035202ceede26330e4a60e0

During the testing make sure that providers details are loaded.
Moreover, video tutorials displayed after first startup. Plus tutorials icon/button is available

Note: for providers make sure to enable every item even with invalid creds

**Comment by dhreben** [comment]
Fixed.
