### ISSUE TITLE
sync email template with latest version

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/minio-storage#4]
due to the refactoring in known issues tracking we have to adjust `test_run_results.ftl` template as well otherwise export to html and sending email is broken

**Comment by vdelendik** [comment]
fixed and pushed changes to the zebrunner; branch: develop.
to test 
1. setup zebrunner CE using develo pbranch
2. run web test
3. link any issue to the failed test
4. export run to html
-> html file is generated and ticket exists in exported html file
5. configure valid jira integration
6. export test run again
-> html file is generated and ticket with valid links exists in exported html file

**Comment by dhreben** [comment]
Fixed
